# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='something about this book'),
            preserve_default=False,
        ),
    ]
